### PR TITLE
Grade for Class 3 Assignment

### PR DESCRIPTION
**Pull request by ryansobol**
Good job, Jeff.
#### Exercise 1
- No crashes, works as expected. 4 points
- Watch the indentation inside `while` loops
- Favor the shorthand reassignment operators whenever possible
#### Exercise 2
- No crashes, however it doesn't work as expected. 3 points
- The output should be `"NO, NOT SINCE 1930!"` when the user inputs text in all caps
- The output should be `"HUH?! SPEAK UP, SONNY!"` when the user inputs text that's not in all caps
- The program should stop running when the user types in `"BYE"`
#### Exercise 3
- No crashes, however it doesn't work as expected. 3 points
- The output is incorrect, just like exercise 2. However, I'm not going to penalize you twice. +1 point
- The `bye_count` logic is perfect, just watch your indentation.
#### Exercise 4
- No crashes, works as expected. 4 points
- I thought you might like to see what your solution might look like if it was rewritten to be shorter.
#### Total

`4 + 3 + 3 + 1 + 4 = 15` :star:

### CODE REVIEW

**Comment by jlebrun** [comment]
Okay thanks. Can you elaborate on the instructions for exercise 3 this week
(Class 4)?

I'm not that clear on what the goal of the exercise is. What is the point
of removing the answer variable? Isn't the entire point of the program to
keep track of whether or not the answer is true or false?

**Comment by ryansobol** [comment]
Sure. The exercise `class4/3_improved_ask_method.rb` wants you to use the `return` keyword to explicitly return a value from the `ask` method.

Re-read section 9.4 and study the code samples closely.

**Comment by jlebrun** [comment]
I don't understand why you need to use return to exit from the loop, or how
that even works. Doesn't return just return a value?

**Comment by ryansobol** [comment]
Right, `return` exits a method by returning a value.

But in addition, if a program executes `return` inside a loop, which is itself inside a method, the loop stops looping and the method exits prematurely. 

Take a look at this method:

``` ruby
def mystery
  count = 0

  loop do
    return count if count == 2
    count += 1
  end
end

puts mystery
```

Run it on your computer. 

What's displayed to you screen when the `mystery` method is run? Do you understand why?

**Pull request merged**
